[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js için tüm rotaları işlemesi için bu yönlendirmeyi kaldırıyoruz
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200 